name: relax
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.3

  #Core
  stacked: ^1.2.1+1
  provider: ^4.0.5
  logger: ^0.8.3
  intl: ^0.16.1
  # State
  #provider: ^4.0.2
  # Data
  #  json_annotation: ^2.4.0
  dio: ^3.0.9
  rxdart: ^0.24.0
  shared_preferences: ^0.5.6+3
  sprintf: ^4.0.2
  # UI
  oktoast: ^2.3.1+1
  pull_to_refresh: ^1.5.8
  cached_network_image: ^2.1.0+1
  flutter_svg: ^0.17.4
  #Library
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.5
  image_picker: ^0.6.5+2
  datetime_picker_formfield: ^1.0.0
  #Map
  flutter_typeahead: ^1.8.0
  flutter_map: ^0.9.0
  flutter_map_marker_cluster: ^0.2.8
  google_maps_flutter: ^0.5.27+2
  flutter_google_places: ^0.2.5
  google_map_polyline: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/roboto_light.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/roboto_medium.ttf
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  assets:
    - assets/icon/
    - assets/images/
flutter_intl:
  enabled: true
