name: relax
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.3

  #Core
  provider_architecture: ^1.0.6
  logger: ^0.8.3
  # State
  #provider: ^4.0.2
  # Data
  #  json_annotation: ^2.4.0
  dio: ^3.0.9
  rxdart: ^0.22.5
  shared_preferences: ^0.5.6+3
  localstorage: ^3.0.1+4
  sprintf: ^4.0.2
  # UI
  oktoast: ^2.3.1+1
  pull_to_refresh: ^1.5.8
  cached_network_image: ^2.0.0
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/roboto_light.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/roboto_medium.ttf
  assets:
    - assets/icon/
    - assets/images/
flutter_intl:
  enabled: true
